### ISSUE TITLE
Auto copy "skypeit (800) 555-5555x1234" to clipboard for easy sharing after running command

### ISSUE THREAD

**Issue by icecreammatt** [staxmanade/skypeit#4]
Add a flag to the .skypeitrc which would automatically copy the command with arguments to the clipboard for easy sharing via skype. I suggest flag since it might bug some people to have it in as a default.

Usage: `skypeit "(800)555-1234x123"`
`command+v` would paste the above typed message.

**Comment by staxmanade** [comment]
note for myself: https://gist.github.com/phette23/a7eb5d95a3ed8d2eef83

**Comment by staxmanade** [comment]
@icecreammatt - `npm install -g skypeit` to get the latest version and add the following to your `~/.skypeitrc`

```yaml

# Places the skype command into the clipboard
# for easily sharing with your team
copyCommandToClipboard: true
```
